# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f9db83682b9b574867e9a08f420ed48024b3e826eec21a632603652b724d03a6a129712f231b78c1bf5f171b79caf5f6427ee6b3025ce0f62e9504ccf33ea15

test:
  secret_key_base: 17edff4dbc58992460be47029728db7206b3a76fef81a4c28b2f2a49735c90bf526960c9bdf0f72bf1f3a19e6ad688d5c60c15b5df723a6493d2c7dca4cbca72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
